### PR TITLE
Update eslint plugin import linter version

### PR DESCRIPTION
**Pull request by bertil291utn**
Update this version to avoid "import-nocycle" [issue](https://github.com/airbnb/javascript/issues/2331) on react projects

### CODE REVIEW

**Comment by bolah2009** [comment]
Hi, @bertil291utn Could you please explain what the issue is? Maybe an example of PR with this issue. Can you also show a an example of how updating the version solved the issue? Thanks! 🙂

**Comment by bertil291utn** [comment]
Hi @bolah2009 
Sure.

Eslint plugin import is given errors related to 
```bash
Configuration for rule "import/no-cycle" is invalid:
Value "∞" should be integer.
```

This error is due to a non updated version, and therefore it's necessary to add an updated eslint-plugin-import version on linter.yml file 

Line 19
update to 
`eslint-plugin-import@2.22.x `

Hope my explanation was clear

Cheers.

**Comment by Spayco** [comment]
@bertil291utn just a heads up, you have conflicts that should be fixed on here, it's of the updated ESLint version (check #109) so make sure it doesn't get outdated again on this PR

**Comment by defoebrand** [comment]
How did we get from 
image
which correctly updates the  eslint-plugin-import version to 
image
being the last activity here?

**Comment by bolah2009** [comment]
@bertil291utn ☝🏽

**Comment by bertil291utn** [comment]
Hi @bolah2009 
I just update to the required/last version to avoid this issue

```bash
Configuration for rule "import/no-cycle" is invalid:
Value "∞" should be integer.
```

Please let me know if this suggestion is ready to merge or if I have to make another change.

**Comment by bolah2009** [comment]
Thanks, @bertil291utn for the PR!!!

Thank you

**Comment by bertil291utn** [comment]
Thank you, sorry because of the time delay

**Comment by bertil291utn** [comment]
Thank you, 👍 

and sorry because of the time delay

**Pull request merged**
