### PR TITLE
Bump up outdated packages

### LINKED ISSUE #141: Getting error while installing eslint-config-airbnb plugin for ESLint.
During the linter config in my redux based project I am facing the problem related to Eslint config installation.

When I run `npm install --save-dev eslint@7.11.x eslint-config-airbnb@18.1.x eslint-plugin-import@2.22.x eslint-plugin-jsx-a11y@6.2.x eslint-plugin-react@7.20.x eslint-plugin-react-hooks@2.5.x babel-eslint@10.1.x` , I am getting this error:

```
Debugger attached.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-bookstore-cms@0.1.0
npm ERR! Found: eslint@7.11.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.11.x" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0" from eslint-config-airbnb@18.1.0
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"18.1.x" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/dere/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dere/.npm/_logs/2021-03-22T19_38_55_657Z-debug.log
Waiting for the debugger to disconnect...
```
I have created the project with `create-react-app` script. Even to solve the problem, I removed package-lock.json file and run `npm install` again too. It didn't solve the problem.

### PR DESCRIPTION
**Pull request by Spayco**
We've had to update ESLint for React so it works with the latest version of it (see #109), but there are 2 packages that should've also been updated to work with the new ESLint version. for some reason, they worked fine on `npm@6`, but not on `npm@7`.

Updated `eslint-plugin-react-hooks@2.5.x` to `eslint-plugin-react-hooks@4.1.x` [[see changelog](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md)]
Updated `eslint-config-airbnb@18.1.x` to `eslint-config-airbnb@18.2.x` [[see changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md)]

I've also **updated all packages** to their latest version so they work with new Node or Ruby versions.

tested and everything should work fine.

Fixes #141

### CODE REVIEW

**Comment by bolah2009** [comment]
@Spayco could you check this https://github.com/microverseinc/linters-config/pull/127#issuecomment-802977679?

I think it would be better to use this PR to bump Github action versions in all the linter config too.

**Comment by Spayco** [comment]
@bolah2009 I made the changes, I've also changed `babel-eslint@10.1.x` to `@babel/eslint-parser@7.x` since `babel-eslint` is deprecated and got replaced by the `@babel/eslint-parser` one

**Comment by Spayco** [comment]
@uryelah @euqueme please have a look and tell me what you think

**Review by uryelah — APPROVED** [review]
Looks good to me :-)

**Review by euqueme — APPROVED** [review]
Works Beautifully on my [html & css](https://github.com/euqueme/using-bootstrap/pull/2), [ruby](https://github.com/SantiagoGuerra/tic-tac-toe/pull/9) ,and [ror](https://github.com/euqueme/workagram/pull/15) projects :ok: :relieved:

**Pull request merged**
