### PR TITLE
Extend CSS dictionary to recognize fit-content property for width

### PR DESCRIPTION
**Pull request by RamseyNjire**
This pull request is a follow-up to [this issue](https://github.com/microverseinc/linters-config/issues/131#issuecomment-804955908). The changes have been implemented.

### CODE REVIEW

**Comment by Spayco** [comment]
hey @RamseyNjire, did you test the change?

**Comment by RamseyNjire** [comment]
@Spayco Yes, I did. This is the exact same change as I made on the [original pull request](https://github.com/microverseinc/ror-social-scaffold/pull/297).

**Comment by Spayco** [comment]
@bolah2009 @RamseyNjire, I tried to replicate the issue, but it didn't show me any error, there might have been an update that fixed it, can you try again?

**Comment by RamseyNjire** [comment]
You need to run stylelint on an existing Microverse project to see the error, such as ror-social-scaffold. This won't work, though, since when my pull request was merged the csstree validator began working properly. Checks pass now. But you can try it locally as follows:


First, clone the [microverse-ror-social-scaffold repo](https://github.com/microverseinc/ror-social-scaffold).

Open a new branch for demo purposes and then use the previous .stylelintrc.json file.

```
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-scss", "stylelint-csstree-validator"],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "csstree/validator": true
  },
  "ignoreFiles": ["build/**", "dist/**", "**/reset*.css", "**/bootstrap*.css"]
}
```

This is the same one as the one currently in [this linters config repo](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json).


Now, when you run `npx stylelint "**/*.{css,scss}"` you should get the error(of course assuming you have stylelint installed locally).

Meanwhile, here is the error on my side. I ran stylelint on the ror social scaffold project.

Stylelint version is:

stylelintversion

And the error is here:

csstreeerror


I have done a pull request [here](https://github.com/microverseinc/ror-social-scaffold/pull/331) and it passes the checks only because we had merged my corrections into the master branch [here](https://github.com/microverseinc/ror-social-scaffold/blob/master/.stylelintrc.json) lines 10 through 12.


When you update the .stylelintrc.json file to the [latest one](https://github.com/microverseinc/ror-social-scaffold/blob/master/.stylelintrc.json):

```
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-scss", "stylelint-csstree-validator"],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "csstree/validator":
    {
      "properties": {
        "width": "| fit-content"
      }
    }
  },
  "ignoreFiles": ["build/**", "dist/**", "**/reset*.css", "**/bootstrap*.css"]
}
```

And then run `npx stylelint "**/*.{css,scss}"`, everything should be fine. 


Even with the latest versions of stylelint and csstree-validator, the error remains.


Currently, this remains an unsolved issue on the [main issue page](https://github.com/csstree/stylelint-validator/issues/29). The only way around it is to manually extend the dictionary as shown [here](https://github.com/csstree/stylelint-validator#options).

**Comment by RamseyNjire** [comment]
@Spayco, @bolah2009, @uryelah I hope that helps!

**Review by Spayco — COMMENTED** [review]
Thanks for the detailed reply, 

I still couldn't replicate the issue, maybe I'm doing something wrong?

here's what I did

`.stylelintrc.json`:

```json
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-scss", "stylelint-csstree-validator"],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "csstree/validator": true
  },
  "ignoreFiles": ["build/**", "dist/**", "**/reset*.css", "**/bootstrap*.css"]
}

```

`CSS`:

```css
h1 {
  width: fit-content;
}
```
`output`:

image

**Comment by RamseyNjire** [comment]
@Spayco I'm not sure why the error doesn't seem replicable when working in the linters config with a single css rule. Here's the thing, though: If you fork the [ror-social-scaffold repo](https://github.com/microverseinc/ror-social-scaffold), then change the stylelintrc.json file to match the one above, that like so:

```
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-scss", "stylelint-csstree-validator"],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "csstree/validator": true
  },
  "ignoreFiles": ["build/**", "dist/**", "**/reset*.css", "**/bootstrap*.css"]
}
```

And then run the `npx stylelint "**/*.{css,scss}" command, you will get the below error:

csstreeerror

Again, please clone the repo and set the stylelintrc.json file to the same as above to see the error in action. Note that the versions for stylelint are the same in the linters.yml files for both the ror-social-scaffold repo and this repo.

Please check it out to see the error in action.

**Comment by bolah2009** [comment]
@RamseyNjire I think `stylelint-csstree-validator` have updated their code to support this property value. Testing it on my side also does not give this error again. Could you try deleting `nodes_modules` and package_lock.json file and reinstall it. Then try the command again?

Or check if you have version `1.9` in your package_lock.json:
Below is the version I tested it with (found in the `package_lock.json` file)
```json
    "stylelint-csstree-validator": {
      "version": "1.9.0",
      "resolved": "https://registry.npmjs.org/stylelint-csstree-validator/-/stylelint-csstree-validator-1.9.0.tgz",
      "integrity": "sha512-fVbtWDEWzux/bZSPBk9tD/bvyc8bSmb52BvUDjcduOzXqKqOyFHUvFayVr9ic88l8KJEVV0Ujab9ah5oTdX4Uw==",
      "dev": true,
      "requires": {
        "css-tree": "^1.0.0"
      }
    }
```

**Comment by bolah2009** [comment]
@RamseyNjire see this commit for more context https://github.com/csstree/csstree/commit/1ece8396aa9ced99b5930999d949bef0c270a68c

**Comment by bolah2009** [comment]
Closing this issue since there's a fix for it already with version update.

**Comment by bolah2009** [comment]
Thanks @RamseyNjire for the MR...

**Pull request closed without merging**
