### PR TITLE
Ignore tailwindcss directives

### PR DESCRIPTION
**Pull request by ahangarha**
Regarding issue #179

### CODE REVIEW

**Comment by od-c0d3r** [comment]
LGTM, @ahangarha 

Should we edit the `.stylelintrc` in `ror` and `react-redux` directories ?

**Comment by ahangarha** [comment]
> Should we edit the `.stylelintrc` in `ror` and `react-redux` directories ?

Thanks for asking.
I didn't make changes in those projects since I didn't have chance to test them. I tested this commit on regular html/css/js projects. I guess it should work on those projects but not sure.

If you don't mind, that could be another PR after proper test.

**Comment by ahangarha** [comment]
@od-c0d3r I just checked this file for React projects and it is working perfectly.

I added a new commit.

**Comment by od-c0d3r** [comment]
Thanks @ahangarha you motivated me ^^,
i have gone and opened a [pr](https://github.com/microverseinc/linters-config/pull/187) for ror linter

**Comment by ahangarha** [comment]
It is good that it is working find on RoR projects as well.

I hope soon it gets merged. I would love to use Tailwindcss in my React projects.

**Comment by ahangarha** [comment]
Is there there any issue with this PR preventing it from being merged? I what to use Tailwindcss in my projects but also don't want to violate the rules and manipulate stylelint config.

**Comment by bellom** [comment]
@ahangarha - Sorry for the late merge 🙂, we needed to make sure all cases work fine.

Thank you for your time on this.

@davidosky007 - Thank you for testing!

**Pull request merged**
