### PR TITLE
Update instructions to use Yarn instead of npm

### PR DESCRIPTION
**Pull request by Spayco**
when using `npx create-react-app` it will install everything in yarn, and create a `yarn.lock` file, then when you use these instructions, you'd use npm, which creates `package-lock.json`, it is not recommended to use both at the same time, and Heroku would tell you to remove one as you can see in the image below:

image

so since react would force us to use yarn, I've changed the instructions here to use it instead of npm, so that way students wouldn't face this problem or get confused which to keep.

### CODE REVIEW

**Comment by Spayco** [comment]
@uryelah please have a look

**Comment by MauricioRobayo** [comment]
Nice!

Just wanted to mention this (from [here](https://create-react-app.dev/docs/getting-started/#selecting-a-package-manager)):

> When you create a new app, the CLI will use Yarn to install dependencies (when available). If you have Yarn installed, but would prefer to use npm, you can append --use-npm to the creation command. For example:

```
npx create-react-app my-app --use-npm
```

And I think each day is becoming more popular to use  `create-react-app` as a initializer with `npm` (which, of course, will use `npm` as the package manager):

```
npm init react-app my-app
```

**Comment by Spayco** [comment]
this is good info @MauricioRobayo, maybe then we should change the pathwright to use npm @nidalaa?

**Comment by bolah2009** [comment]
Thanks, @Spayco, I think I like @MauricioRobayo approach better (thanks @MauricioRobayo), but let me discuss this with the learning team. Until then we can keep this PR open.

**Comment by nidalaa** [comment]
@bolah2009 I added it as a requirement for the entire module:

- https://microverse.pathwright.com/library/react-redux-v10/188148/path/step/107676519/
- https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376012/
please go ahead and merge it 👍 

@Spayco @MauricioRobayo good job here! 👏

**Comment by Spayco** [comment]
@nidalaa this PR would change linters to use `yarn`, so I guess we should close it instead?

**Comment by nidalaa** [comment]
Good catch @Spayco ! 😈

**Pull request closed without merging**
