### PR TITLE
Changes to the rules to be consistent with stickler errors.

### PR DESCRIPTION
**Pull request by jofer86**
## This PR creates a hotfix for the current errors being brought up in the Full-time students challenge.

- They consist of the following, the error that was brought to us was that the stickler check was bringing an error related to the arrow-parens rule which states, according to the documentation, that even if there is only one parameter being passed in an arrow function it does require for it to be enclosed in parens. But the stickler check thinks otherwise, and since there is no way to bypass this error, the only solution would be to turn off the arrow-parens rule in the local environment so that we can have a consistent linting in all stages of development.

- The change proposed for the react section follows along with the same principles. And there is also a change in the README file to be more consistent with the Javascript section one.

### CODE REVIEW

**Comment by nidalaa** [comment]
Thnaks @jofer86 ! :)

**Comment by efrapp** [comment]
Hi @jofer86 and @bolah2009,
I was checking the change introduced in this PR turning off the `arrow-parens` rule completely and I think it is too restrictive. According to the Eslint documentation for the [`arrow-parens`](https://eslint.org/docs/rules/arrow-parens) rule:

> Arrow functions can omit parentheses when they have exactly one parameter. In all other cases, the parameter(s) must be wrapped in parentheses. This rule enforces the consistent use of parentheses in arrow functions.

So the way I think we can achieve this is using the following rule:
```
"arrow-parens": [2, "as-needed", { "requireForBlockBody": true }]
```
> The `"as-needed"` enforces no braces where they can be omitted and
`"requireForBlockBody": true` modifies the as-needed rule to require parens if the function body is in an instructions block (surrounded by braces).

It is difficult to know what is the default configuration Stickler use because they don't say anything in the docs but I think they are aligned to Eslint too.

Please, let know your thoughts.

**Comment by bolah2009** [comment]
Hi @efrapp, please check out https://github.com/microverseinc/linters-config/pull/49 and let me know your thoughts...

**Comment by efrapp** [comment]
Already checked. I left my thoughts there.

**Pull request merged**
