### PR TITLE
Bash script to compare linters files

### PR DESCRIPTION
**Pull request by MauricioRobayo**
# check-linters-confg

`check-linters-config` is a bash script to compare local files against the files on the master branch of this repository. It will Check that files exist and that they are identical to the ones here.

## Installation

1. Copy the [`check-linters-conf.sh`](check-linters-conf.sh) file into someplace in the `$PATH` of your machine, for example `/usr/local/bin`:

```sh
sudo wget -O /usr/local/bin/check-linters-config https://raw.githubusercontent.com/MauricioRobayo/linters-config/feature/verification-script/scripts/check-linters-conf.sh
```

2. Make it executable:

```
sudo chmod +x /usr/local/bin/check-linters-config
```

## Usage

Run the command `check-linters-config` on the root of the repository you want to check. It takes as an argument the name of the directory you want to check against.

```sh
$ check-linters-config ruby
Files master/ruby/.stickler.yml and .stickler.yml differ
Files master/ruby/.rubocop.yml and .rubocop.yml are identical
```

The possible directories/options included are:

- [css](https://github.com/microverseinc/linters-config/tree/master/css)
- [javascript](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [react-redux](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- [ror](https://github.com/microverseinc/linters-config/tree/master/ror)
- [ruby](https://github.com/microverseinc/linters-config/tree/master/ruby)

### CODE REVIEW

**Comment by gootyfer** [comment]
Hi @MauricioRobayo Thanks a lot for making this happen :)

My first question is: is this tool useful for TSEs checking repos, for students or both? 
If it is for students, please add small instructions in the README (similar to those in this PR) so that anyone could know how to use it. Is it is something useful for TSEs too, maybe you should also add something to TSE docs about the availability of this new tool.

Many thanks again, and update here what do you think about my request.

**Comment by MauricioRobayo** [comment]
Thanks @gootyfer , I should have explained how is this useful 🤣.

This is for TSEs. I kept missing that requirement on my reviews and it takes some time to do it, so I automated the process so we TSEs don't have an excuse to miss that step and we can do it in a second.

I will add instructions on the TSEs docs. Maybe, in that case, this shouldn't be here 😣. Feel free to close this PR if you agree and I'll move the script and the instructions to the `useful tools` on the TSEs guidelines.

**Comment by gootyfer** [comment]
Thanks @MauricioRobayo ! I agree that this is valuable for TSEs, for sure. But should it be something valuable also for students? For example, we told them to use a config file and using this tool they can check if they did a good configuration. Or is it a bit overkill only for this use case?

**Comment by MauricioRobayo** [comment]
Good point @gootyfer!

So here it is 😁:

- [x] Add a [README.md](https://github.com/MauricioRobayo/linters-config/tree/feature/verification-script/scripts/README.md) to the scripts folder next to the script file with instruction on how to use. The links are pointing to this repo so are not working yet since it is not merged.
- [x] Add a [**Validation** section](https://github.com/MauricioRobayo/linters-config/tree/feature/verification-script#validation) to the main README.md on this repo, with the following content.
- [ ] Add it to the useful tools on the TSEs guidelines.

Thanks for the feedback, I think it's coming into place.

**Pull request merged**
